version: '3.8'
services:
  db:
    image: postgres:14
    container_name: horus_heresy_db
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - horus_heresy_network

volumes:
  db_data:

networks:
  horus_heresy_network:
